"""Contains implementations of XOF functions as needed for ML DSA"""

from _hashlib import HASHXOF

class XOF:
  """XOF object as per NIST expectations"""
  BLOCK_SIZE = 64
  """Size of a single regeneration block"""
  def __init__(self, h: HASHXOF):
    """
    XOF object as per NIST expectations

    Args:
      h (HASHXOF): The hash object, may be initialized with seed
    """
    self.__h = h
    self.__xof_ix = 0
    self.__xof_output = b''
    self.__xof_output_ix = 0

  def _regenerateOutput(self, min_len: int):
    """
    Get new output of length at least min_len
    """
    # First save the current unused output
    self.__xof_output = self.__xof_output[self.__xof_output_ix:]
    self.__xof_output_ix = 0
    gen_len = ((min_len // XOF.BLOCK_SIZE) + 1) * XOF.BLOCK_SIZE
    self.__xof_output += self.__h.digest(self.__xof_ix + gen_len)[self.__xof_ix:]
    self.__xof_ix += gen_len

  def Squeeze(self, l: int) -> bytes:
    """
    Get l bytes of output from XOF

    Args:
      l (int): How many bytes to return

    Returns:
      The generated bytes
    """
    # Check if there is not enough output
    if len(self.__xof_output) - self.__xof_output_ix < l:
      self._regenerateOutput(l)
    ret = self.__xof_output[self.__xof_output_ix:self.__xof_output_ix + l]
    self.__xof_output_ix += l
    return ret

  def Absorb(self, data: bytes):
    """
    Update the XOF with the data

    Args:
      data (bytes): Data to update the XOF with

    Raises:
      RuntimeError: Cannot Absorb after Squeeze
    """
    if self.__xof_ix != 0: raise RuntimeError('Cannot Absorb after Squeeze')
    self.__h.update(data)
