"""
A collection of RNG functions for ML KEM
"""

from hashlib import shake_128, shake_256, sha3_256, sha3_512

from constants import Q, N, MATRIX_SAMPLE_BOUND
from encoding import bytes_to_bits

_MATRIX_GEN_XOF_STEP_SIZE = 99

def generateMatrixPolynomial(rho: bytes, inp_j: int, inp_i: int) -> list[int]:
  """
  Generate coefficients of the matrix polynomial

  Args:
    rho (bytes): The matrix seed
    inp_j (int): The second coord of the loop (inner)
    inp_i (int): The first coord of the loop (outer)

  Returns:
    A list representing coefficients of the polynomial

  Raises:
    RuntimeError: When the upper while loop boundary is overstepped
  """
  seed = rho + inp_j.to_bytes() + inp_i.to_bytes()
  xof = shake_128(seed)
  xof_ix = 0
  safety_index = 0
  ret = []
  while len(ret) < N:
    cur_bytes = xof.digest(xof_ix + _MATRIX_GEN_XOF_STEP_SIZE)[xof_ix:]
    xof_ix += _MATRIX_GEN_XOF_STEP_SIZE
    i = 0
    while i < _MATRIX_GEN_XOF_STEP_SIZE:
      d1 = cur_bytes[i] + 256 * (cur_bytes[i+1] % 16)
      d2 = cur_bytes[i+1] // 16 + 16 * cur_bytes[i+2]
      if d1 < Q: ret.append(d1)
      if d2 < Q and len(ret) < N: ret.append(d2)
      i += 3
    safety_index += 1
    if safety_index > MATRIX_SAMPLE_BOUND: raise RuntimeError('ML-KEM.KeyGen: Matrix generation entered infinite while loop')
  return ret

def prf(seed: bytes, b: int, eta: int) -> bytes:
  """
  Pseudo random function

  Args:
    seed (bytes): Random seed
    b (int): Unique int for sampling
    eta (int): The range of the CBD

  Returns:
    A byte string of length 64 * eta
  """
  shake = shake_256(seed + b.to_bytes())
  return shake.digest(64 * eta)

def generateSmallPolynomial(bs: bytes, eta: int) -> list[int]:
  """
  Generate small coefficients for a polynomial

  Args:
    bs (bytes): The byte string generated by prf
    eta (int): The range for the coefficients

  Returns:
    A list of coefficients

  Raises:
    IndexError: The provided byte string is too short
  """
  if len(bs) < eta * 64: raise IndexError(f'The provided byte string is too short for {eta=}')
  b = bytes_to_bits(bs)
  ret = []
  for i in range(N):
    x = sum([b[2 * i * eta + j] for j in range(eta)])
    y = sum([b[2 * i * eta + eta + j] for j in range(eta)])
    ret.append((x - y) % Q)
  return ret


def hashG(inp: bytes) -> bytes:
  """
  The hash function denoted by G

  Args:
    inp (bytes): Input to the hash function

  Returns:
    The resulting hash bytes (64 bytes)
  """
  return sha3_512(inp).digest()

def hashH(inp: bytes) -> bytes:
  """
  The hash function denoted by H

  Args:
    inp (bytes): Input to the hash function

  Returns:
    The resulting hash bytes (32 bytes)
  """
  return sha3_256(inp).digest()

def hashJ(inp: bytes) -> bytes:
  """
  The hash function denoted by J

  Args:
    inp (bytes): Input to the hash function

  Returns:
    The resulting hash bytes (32 bytes)
  """
  return shake_256(inp).digest(32)
